language: cpp

sudo: required
dist: trusty

env:
  global:  
   - GTEST_DIR=${TRAVIS_BUILD_DIR}/gtest

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-3.6
    packages: &native_deps
    - cmake
    - doxygen
    - clang-3.6
    - libusb-1.0-0-dev
    - libfftw3-dev
    - libqt5qml5
    - libgtest-dev
    - libqt5opengl5-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - gcc-5
    - g++-5
    - gcc-4.8
    - g++-4.8

# We are testing
# * linux with g++4.8 and g++5 and clang 3.6
# * osx with clang 3.6
matrix:
  include:
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=g++-4.8
      os: linux
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=g++-5
      os: linux
    - compiler: clang
      env: CMAKE_CXX_COMPILER=clang++-3.6
      os: linux
    - compiler: clang
      env: CMAKE_CXX_COMPILER=/usr/bin/clang++
      os: osx
  
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install libusb fftw qt5; export CMAKE_PREFIX_PATH=$(brew --prefix qt5); fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then mkdir $HOME/usr; export PATH="$HOME/usr/bin:$PATH"; wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh; chmod +x cmake-3.7.2-Linux-x86_64.sh; ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license; fi

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH ../

script:
    - make

before_deploy:
    - make package

notifications:
  on_success: change
  on_failure: always

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kIX221nPUe3OM5CNeEJ1iyRg2FFpmlL7c+uxJS11+HBRcFTGCIArHoxMIUb1u289+Co0jp42BVxhpo9PaKhHhzy3iVsKM1xOty3GAr9/1KzVnvJY0dOWqO2cYks4w24WF50ii3kUtYGVKpJrsHPT8UeI2z+taYr1jBmKkoYuoWDG+3CAZytLAsOVDRPylhzSD8B+OrCHIbN1npcitEpFUMJWgvDVi6ZKsz8o6obs/NhwFEc9TBDhS7CeIoAcNt7S0WdDM4ZyHyOeYShWxL0DlZBuhvS7SVZbxy/DS/cTAyoaWqgFLQokmhsKkVIytnq40kC9kGUZvoSpfwtfnA55eElFP5sNbnjQEUaDgq8Doi+aTTc7WRmhBCJbmz6RlqPAECQzx67JuTukV7F6Ds6B34+9naV3dAhj7dnMAoIvY1UK4NhvT+w3aQNR3B93TLZfYHvAmVoZcMGEY/EqLbHdMdJ7E9YGEQQUXW/753EmulCu9/O/gEs+8DlNc1ejFUGJhQmTyJBOLupJpFanC+6mTcbSGlJLwAHxL5yuJ0x5xLzZvJ9jTJI1QFu8ZztFw6gPCBpxPVle6E/Ht3CIByoK5RtKzhJBxgYDG+k0Yaqgbp1wh1ET56xEj8GxQlTKW43Mwbt4aXAarZ11C3erab5lCQyubIUXuq0TWxJLDTfOC6I=
  file: "packages/OpenHantekProject-*"
  on:
    repo: OpenHantek/openhantek
    condition: "$CMAKE_CXX_COMPILER = clang++-3.6"
    tags: true
