title: Openhantek
description: Software for Hantek and compatible (Voltcraft/Darkwire/Protek/Acetech) USB digital signal oscilloscopes
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions

exclude:
  - .gitignore
  - CNAME
  - readme.md

logo: images/openhantek.png
